// Message type constants for chrome.runtime messaging
export const MSG = {
  // DLP
  DLP_SCAN: 'DLP_SCAN',
  DLP_SCAN_RESULT: 'DLP_SCAN_RESULT',

  // Web3
  WEB3_INTERCEPT: 'WEB3_INTERCEPT',
  WEB3_INTERCEPT_RESULT: 'WEB3_INTERCEPT_RESULT',

  // Settings
  GET_SETTINGS: 'GET_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',

  // Overlay
  SHOW_TOAST: 'SHOW_TOAST',
  SHOW_ALERT_PANEL: 'SHOW_ALERT_PANEL',
  ALERT_PANEL_RESPONSE: 'ALERT_PANEL_RESPONSE',

  // Logs
  GET_LOGS: 'GET_LOGS',
  CLEAR_LOGS: 'CLEAR_LOGS',
} as const;
